config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from settings_app.views import AdminView
from settings_app.language import set_language

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="MEGANO payment API",
        default_version="v1",
        description="This api is used for getting payments through random account",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="megano@megano.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("i18n", set_language, name="set_language"),
    path("admin/", admin.site.urls),
    path("admin/", include("admin_tools.urls")),
    path("api_auth/", include("rest_framework.urls")),
    path("api/", include("payments_app.urls")),
    path("settings-admin/", include("settings_app.urls", namespace="settings-polls")),
    path("", include("goods_app.urls", namespace="goods-polls")),
    path("users/", include("profiles_app.urls", namespace="profiles-polls")),
    path("accounts/", include("allauth.urls")),
    path("orders/", include("orders_app.urls", namespace="orders-polls")),
    path("stores/", include("stores_app.urls", namespace="stores-polls")),
    path("discounts/", include("discounts_app.urls", namespace="discounts-polls")),
    path("swagger/", schema_view.with_ui("swagger", cache_timeout=0), name="schema-swagger-ui"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goods_app/urls.py
from django.urls import path
from goods_app.views import IndexView, ProductDetailView, get_reviews, post_review, FullCatalogView, AllCardForAjax

app_name = "goods"
urlpatterns = [
    path("", IndexView.as_view(), name="index_url"),
    path("product-detail/<str:slug>/", ProductDetailView.as_view(), name="product-detail"),
    path("get_reviews/", get_reviews, name="get_reviews"),
    path("post_review/", post_review, name="post_review"),
    path("catalogs/", FullCatalogView.as_view(), name="catalog_url"),
    path("async_catalog/", AllCardForAjax.as_view(), name="ajax_full"),
]

orders_app/urls.py
from django.urls import path
from orders_app import views

app_name = "orders"
urlpatterns = [
    # эндпоинты корзины
    path("cart/", views.CartView.as_view(), name="cart_detail"),
    path("cart/<int:product_id>", views.CartView.as_view(), name="cart_detail_post"),
    path("add/<int:product_id>/", views.CartAdd.as_view(), name="cart_add"),
    path("add/<int:product_id>/", views.CartAdd.as_view(), name="cart_add_many"),
    path("remove/<int:product_id>/", views.CartRemove.as_view(), name="cart_remove"),
    path("clear/", views.cart_clear, name="cart_clear"),
    # эндпоинты оформления заказа
    path("step1/", views.OrderStepOne.as_view(), name="order_step_one"),
    path("step11/", views.OrderStepOneAnonym.as_view(), name="order_step_one_anonymous"),
    path("step2/", views.OrderStepTwo.as_view(), name="order_step_two"),
    path("step3/", views.OrderStepThree.as_view(), name="order_step_three"),
    path("step4/", views.OrderStepFour.as_view(), name="order_step_four"),
    # эндпоинты оплаты
    path("payment/<int:order_id>", views.PaymentView.as_view(), name="payment"),
    path("payment/card/<int:order_id>", views.PaymentWithCardView.as_view(), name="payment_with_card"),
    path("payment/account/<int:order_id>", views.PaymentWithAccountView.as_view(), name="payment_with_account"),
    path("done/", views.payment_done, name="payment_done"),
    path("canceled/", views.payment_canceled, name="payment_canceled"),
    # эндпоинты товаров для сравнения
    path("compare/", views.CompareView.as_view(), name="compare"),
    path("compare/add/<int:product_id>/", views.AddToCompare.as_view(), name="add-to-compare"),
    path("compare/remove/<str:product_name>/", views.RemoveFromCompare.as_view(), name="remove-from-compare"),
    # эндпоинты истории заказов
    path("history/", views.HistoryOrderView.as_view(), name="history-order"),
    path("history/<int:order_id>", views.HistoryOrderDetail.as_view(), name="history-order-detail"),
    # эндроинты истории просмотров
    path("viewed_history/", views.ViewedGoodsView.as_view(), name="history-view"),
    path("add_viewed/", views.add_viewed, name="add_viewed"),
]

profiles_app/urls.py
from django.urls import path
from profiles_app.views import UserLogin, UserLogout, RegisterView, RestorePasswordView, AccountView, AccountEditView

app_name = "profiles"
urlpatterns = [
    path("login/", UserLogin.as_view(), name="login"),
    path("logout/", UserLogout.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("restore-password/", RestorePasswordView.as_view(), name="restore-password"),
    path("private-room/", AccountView.as_view(), name="private-room"),
    path("private-room/profile/", AccountEditView.as_view(), name="account-edit"),
]

stores_app/urls.py
from django.urls import path
from stores_app import views


app_name = "stores"
urlpatterns = [
    path("add-store/", views.AddNewStoreView.as_view(), name="add-store"),
    path("add-store-product/", views.AddSellerProductView.as_view(), name="add-store-product"),
    path("sellers-room/", views.SellersRoomView.as_view(), name="sellers-room"),
    path("request-add-new-product/", views.RequestNewProduct.as_view(), name="request-new-product"),
    path("category-filter/", views.CategoryFilter.as_view(), name="category-filter"),
    path("delete-store/", views.remove_Store, name="delete-store"),
    path("delete-seller-product/", views.remove_SellerProduct, name="delete-seller-product"),
    path("edit-store/<str:slug>/", views.EditStoreView.as_view(), name="edit-store"),
    path("stores-list/", views.StoresListView.as_view(), name="stores-list"),
    path("products-list/", views.AllSellerProductView.as_view(), name="all-products-list"),
    path("store-detail/<str:slug>/", views.StoreDetailView.as_view(), name="store-detail"),
    path("<str:slug>/<int:pk>/", views.EditSelleProductView.as_view(), name="edit-seller-product"),
    # discount endpoints
    path("add-store-product-discount/", views.AddProductDiscountView.as_view(), name="add-store-product-discount"),
    path("delete-store-product-discount/", views.remove_ProductDiscount, name="delete-store-product-discount"),
    path(
        "edit-store-product-discount/<str:slug>/<int:pk>/",
        views.EditProductDiscountView.as_view(),
        name="edit-store-product-discount",
    ),
    path("add-store-group-discount/", views.AddGroupDiscountView.as_view(), name="add-store-group-discount"),
    path("delete-store-group-discount/", views.remove_GroupDiscount, name="delete-store-group-discount"),
    path(
        "edit-store-group-discount/<str:slug>/<int:pk>/",
        views.EditGroupDiscountView.as_view(),
        name="edit-store-group-discount",
    ),
    path("add-store-cart-discount/", views.AddCartDiscountView.as_view(), name="add-store-cart-discount"),
    path("delete-store-cart-discount/", views.remove_CartDiscount, name="delete-store-cart-discount"),
    path(
        "edit-store-cart-discount/<str:slug>/<int:pk>/",
        views.EditCartDiscountView.as_view(),
        name="edit-store-cart-discount",
    ),
    path("import/", views.ImportView.as_view(), name="import"),
]

templates/elems/banner.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block main %}
<div class="Header-slider">
    <div class="Slider Slider_main">
        <div class="Slider-box">
            {% for banner in banners %}
                <div class="Slider-item">
                    <div class="Slider-content">
                        <div class="row">
                            <div class="row-block">
                                <strong class="Slider-title">{{ banner.title }}
                                </strong>
                                <div class="Slider-text">{{ banner.description }}</div>
                                <div class="Slider-footer"><a class="btn btn_primary" href="{% url 'discounts-polls:discount-detail' banner.discount.slug banner.discount.id %}">{% trans 'Get Started' %}</a>
                                </div>
                            </div>
                            <div class="row-block">
                                <div class="Slider-img"><img src="{{ banner.image.url }}" alt="slider.png"/>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="Slider-navigateWrap">
          <div class="Slider-navigate">
          </div>
        </div>
    </div>
</div>
{% endblock %}

templates/elems/card.html
{% load static i18n %}

{% for offer, price_after_discount, discount in products %}
{% if offer.id != exclude.id %}
{% if slider %}
<div class="Slider-item">
    <div class="Slider-content">
{% endif %}
    <div class="Card" style="position: relative; min-height: 392px;">
        <div class="store-name">
            <a href="{% url 'stores-polls:store-detail' offer.seller.slug %}"><img src="{{offer.seller.icon_url}}" alt="store-icon"></a>
        </div>
        <form method="get" action="{% url 'orders-polls:add_viewed' %}">
            <input type="hidden" name="seller_product_id" value="{{ offer.id }}">
            <button class="Card-picture" type="submit" style="max-width: 200px;">
                <img src="{{ offer.product.image_url }}" alt="card.jpg">
            </button>
            <div class="Card-content">
                <button class="Card-title" type="submit" style="min-height: 62px; width: 100%; text-align: center;">
                    {{ offer.product.name }}
                </button>
                <div class="Card-description" style="width: 100%; text-align: center;">
                    <div class="Card-cost">
                        <span class="Card-priceOld">{% if price_after_discount and not discount.set_discount %}${{ offer.price }}{% endif %}</span>
                        <span class="Card-price">
                            {% if price_after_discount and not discount.set_discount %}
                                ${{ price_after_discount|floatformat:0 }}
                            {% else %}
                                ${{ offer.price }}
                            {% endif %}
                        </span>
                    </div>
                    <div class="Card-category">{% if offer.product.category.parent_id %}{{ offer.product.category.parent }} / {% endif %}{{ offer.product.category.name }}</div>
                    <div class="Card-hover">
                        <a class="Card-btn" href="#"><img src="{% static 'assets/img/icons/card/bookmark.svg' %}" alt="bookmark.svg"/></a>
                        <a class="Card-btn" href="{% url 'orders-polls:cart_add' offer.id %}"><img src="{% static 'assets/img/icons/card/cart.svg' %}" alt="cart.svg"/></a>
                        <a class="Card-btn" href="{% url 'orders-polls:add-to-compare' offer.id %}"><img src="{% static 'assets/img/icons/card/change.svg' %}" alt="change.svg"/></a>
                    </div>
                </div>
           </div>
        </form>
        {% if discount.type_of_discount == 'p' and not discount.set_discount %}
        <div class="Card-sale">-{{ discount.percent|floatformat:0}}%
        </div>
        {% elif discount.type_of_discount == 'f' and not discount.set_discount %}
        <div class="Card-sale" style="background-color: #d00d0d">-{{ discount.amount|floatformat:0}}$
        </div>
        {% elif discount.type_of_discount == 'fp' and not discount.set_discount %}
        <div class="Card-sale" style="background-color: #6888fc">!!!
        </div>
        {% endif %}
        {% if seller_perm %}
        <form action="{% url 'stores-polls:delete-seller-product' %}" method="get">
            <input type="hidden" name="id" value="{{ offer.id }}">
            <button type="Submit" class="delete-btn seller-product" title="Delete this product">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
                    <path d="M135.2 17.69C140.6 6.848 151.7 0 163.8 0H284.2C296.3 0 307.4 6.848 312.8 17.69L320 32H416C433.7 32 448 46.33 448 64C448 81.67 433.7 96 416 96H32C14.33 96 0 81.67 0 64C0 46.33 14.33 32 32 32H128L135.2 17.69zM31.1 128H416V448C416 483.3 387.3 512 352 512H95.1C60.65 512 31.1 483.3 31.1 448V128zM111.1 208V432C111.1 440.8 119.2 448 127.1 448C136.8 448 143.1 440.8 143.1 432V208C143.1 199.2 136.8 192 127.1 192C119.2 192 111.1 199.2 111.1 208zM207.1 208V432C207.1 440.8 215.2 448 223.1 448C232.8 448 240 440.8 240 432V208C240 199.2 232.8 192 223.1 192C215.2 192 207.1 199.2 207.1 208zM304 208V432C304 440.8 311.2 448 320 448C328.8 448 336 440.8 336 432V208C336 199.2 328.8 192 320 192C311.2 192 304 199.2 304 208z"/>
                </svg>
            </button>
            <a class="bth-width-store edit-seller-product" href="{{ offer.get_absolute_url }}" title="Edit product">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                    <path d="M373.1 24.97C401.2-3.147 446.8-3.147 474.9 24.97L487 37.09C515.1 65.21 515.1 110.8 487 138.9L289.8 336.2C281.1 344.8 270.4 351.1 258.6 354.5L158.6 383.1C150.2 385.5 141.2 383.1 135 376.1C128.9 370.8 126.5 361.8 128.9 353.4L157.5 253.4C160.9 241.6 167.2 230.9 175.8 222.2L373.1 24.97zM440.1 58.91C431.6 49.54 416.4 49.54 407 58.91L377.9 88L424 134.1L453.1 104.1C462.5 95.6 462.5 80.4 453.1 71.03L440.1 58.91zM203.7 266.6L186.9 325.1L245.4 308.3C249.4 307.2 252.9 305.1 255.8 302.2L390.1 168L344 121.9L209.8 256.2C206.9 259.1 204.8 262.6 203.7 266.6zM200 64C213.3 64 224 74.75 224 88C224 101.3 213.3 112 200 112H88C65.91 112 48 129.9 48 152V424C48 446.1 65.91 464 88 464H360C382.1 464 400 446.1 400 424V312C400 298.7 410.7 288 424 288C437.3 288 448 298.7 448 312V424C448 472.6 408.6 512 360 512H88C39.4 512 0 472.6 0 424V152C0 103.4 39.4 64 88 64H200z"/>
                </svg>
            </a>
        </form>
        {% endif %}
    </div>
{% if slider %}
    </div>
</div>
{% endif %}
{% endif %}
{% endfor %}

templates/elems/good_card.html
{% load static %}
{% load i18n %}

<div id="cards_with_pagination">
    <div class="Cards" id="good_card">
        {% for elem in page_obj %}
        <div class="Card">
            <div class="store-name">
                <a href="{% url 'stores-polls:store-detail' elem.seller.slug %}"><img src="{{elem.seller.icon_url}}" alt="store-icon"></a>
            </div>
            <a class="Card-picture" href="{% url 'orders-polls:add_viewed' %}?seller_product_id={{elem.id}}">
                <img src="{{ elem.product.image_url }}" alt="card.jpg"/>
            </a>
            <div class="Card-content">
                <strong class="Card-title"><a href="{{ elem.product.get_absolute_url }}">{{ elem.product }}</a>
                </strong>
                <div class="Card-description">
                    <div class="Card-cost">

                        {% if elem.price_after_discount %}
                        <span class="Card-priceOld">{{ elem.price }}</span>
                        <span class="Card-price">{{ elem.price_after_discount }}</span>
                        {% else %}
                        <span class="Card-price">{{ elem.price }}</span>
                        {% endif %}

                    </div>
                    <div class="Card-category">{{elem.product.category}}</div>
                    <div class="Card-hover">
                        <a class="Card-btn" href="#">
                            <img src="{% static 'assets/img/icons/card/bookmark.svg' %}" alt="bookmark.svg"/>
                        </a>
                        <a class="Card-btn" href="{% url 'orders-polls:cart_add' elem.id %}">
                            <img src="{% static 'assets/img/icons/card/cart.svg' %}" alt="cart.svg"/>
                        </a>
                        <a class="Card-btn" href="{% url 'orders-polls:add-to-compare' elem.id %}">
                            <img src="{% static 'assets/img/icons/card/change.svg' %}" alt="change.svg"/>
                        </a>
                    </div>
                </div>
            </div>

            {% if elem.discount.type_of_discount == 'p' and not elem.discount.set_discount %}
            <div class="Card-sale">
                -{{ elem.discount.percent|floatformat:0}}%
            </div>

            {% elif elem.discount.type_of_discount == 'f' and not elem.discount.set_discount %}
            <div class="Card-sale" style="background-color: #d00d0d">
                -{{ elem.discount.amount|floatformat:0}}$
            </div>

            {% elif elem.discount.type_of_discount == 'fp' and not elem.discount.set_discount %}
            <div class="Card-sale" style="background-color: #6888fc">
                !!!
            </div>
            {% endif %}

        </div>
        {% endfor %}

    </div>

    {% include 'elems/pagination.html' %}

</div>

templates/elems/header.html
{% load static %}
{% load i18n %}
{% load goods_tags %}


{% include 'elems/menu_head.html' %}
<div class="Header-searchWrap">
    <div class="wrap">
        <div class="Header-categories">
            <div class="CategoriesButton">
                <div class="CategoriesButton-title">
                    <div class="CategoriesButton-icon"><img src="{% static 'assets/img/icons/allDep.svg' %}"
                                                            alt="allDep.svg"/>
                    </div>
                    <span class="CategoriesButton-text">{% trans 'All Departments' %}</span>
                    <div class="CategoriesButton-arrow">
                    </div>
                </div>
                <div class="CategoriesButton-content">

<!--                    {% load mptt_tags %}-->
                    {% get_tree_dict as dict %}

                    {% for key, value in dict.items %}

                    <div class="CategoriesButton-link">
                        <a href="{% url 'goods-polls:catalog_url' %}?slug={{key.slug}}">
                            <div class="CategoriesButton-icon">
                                <img src="{{ key.icon_url }}" alt="image_category" style="width: 100%">
                            </div>
                            <span class="CategoriesButton-text">{{ key.name }}</span>
                        </a>

                        {% if value %}
                        <a class="CategoriesButton-arrow" href="#"></a>
                        <div class="CategoriesButton-submenu">
                            {% for elem in value %}


                            <a class="CategoriesButton-link"
                               href="{% url 'goods-polls:catalog_url' %}?slug={{elem.slug}}">
                                <div class="CategoriesButton-icon">
                                <img src="{{ elem.icon_url }}" alt="image_category" style="width: 100%">
                                </div>
                                <span class="CategoriesButton-text">{{ elem.name }}</span>
                            </a>


                            {% endfor %}
                        </div>
                        {% endif %}
                    </div>

                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="Header-searchLink"><img src="{% static 'assets/img/icons/search.svg' %}" alt="search.svg"/>
        </div>
        <div class="Header-search">
            <div class="search" id="search_div"
                 data-search_query={{ search }}>

                <form class="form form_search" action="{% url 'goods-polls:catalog_url' %}" method="get"
                      name="search_form">
                    <input class="search-input" id="query" name="query" type="text"
                           placeholder="What are you looking for ...">
                    <button class="search-button" type="submit" id="search_btn" onclick="return false;">
                        <img src="{% static 'assets/img/icons/search.svg' %}" alt="search.svg"/>
                        {% trans 'Search' %}
                    </button>
                </form>

            </div>
        </div>
    </div>
</div>

templates/elems/hot_offers.html
{% load static %}
{% load i18n %}
{% load goods_tags %}

  <div class="Section Section_dark">
    <div class="wrap">
      <div class="Section-content">
        <div class="Slider Slider_carousel">
          <header class="Section-header">
            <h2 class="Section-title">{% trans 'Hot Offers' %}
            </h2>
            <div class="Section-control">
              <div class="Slider-navigate">
              </div>
            </div>
          </header>
          <div class="Slider-box Cards Cards_hz">
          {% cards hot_offers slider=True %}
          </div>
        </div>
      </div>
    </div>
  </div>

templates/elems/menu_head.html
{% load static %}
{% load i18n %}
<div class="ControlPanel">
  <div class="wrap">
    <div class="row ControlPanel-row">
      <div class="row-block">
        <div class="row ControlPanel-rowSplit">
          <div class="row-block"><a class="ControlPanel-title" href="#">{% trans 'Free Delivery' %}</a>
          </div>
          <div class="row-block hide_700"><span class="ControlPanel-title">{% trans 'Follow Us' %}</span>
            <ul class="menu menu_img menu_smallImg ControlPanel-menu">
              <li class="menu-item"><a class="menu-link" href="#"><img src="{% static 'assets/img/icons/socialHeader/fb.svg' %}" alt="fb.svg"/></a>
              </li>
              <li class="menu-item"><a class="menu-link" href="#"><img src="{% static 'assets/img/icons/socialHeader/tw.svg' %}" alt="tw.svg"/></a>
              </li>
              <li class="menu-item"><a class="menu-link" href="#"><img src="{% static 'assets/img/icons/socialHeader/in.svg' %}" alt="in.svg"/></a>
              </li>
              <li class="menu-item"><a class="menu-link" href="#"><img src="{% static 'assets/img/icons/socialHeader/pt.svg' %}" alt="pt.svg"/></a>
              </li>
              <li class="menu-item"><a class="menu-link" href="#"><img src="{% static 'assets/img/icons/socialHeader/mail.svg' %}" alt="mail.svg"/></a>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <nav class="row-block">
        <div class="row ControlPanel-rowSplit">
          <div class="row-block">

              {% include 'elems/localize_menu.html' %}

              {% if request.user.is_authenticated %}
                <a class="ControlPanel-title" href="{% url 'profiles-polls:private-room' %}">{% trans 'My Account' %}</a> / <a class="ControlPanel-title" href="{% url 'profiles-polls:logout' %}"> {% trans 'Logout' %}</a>
              {% else %}
                  <a class="ControlPanel-title" href="{% url 'profiles-polls:login' %}">{% trans 'Login' %}</a> / <a class="ControlPanel-title" href="{% url 'profiles-polls:register' %}">{% trans 'Register' %}</a>
              {% endif %}
          </div>
        </div>
      </nav>
    </div>
  </div>
</div>
<div class="wrap">
  <div class="row Header-rowMain">
    <div class="row-block Header-logo"><a class="logo" href="/"><img class="logo-image" src="{% static 'assets/img/logo.png' %}" alt="logo.png"/></a>
    </div>
    <nav class="row-block row-block_right Header-menu">
      <div class="menuModal" id="navigate">
        <ul class="menu menu_main">
          <li class="menu-item"><a class="menu-link" href="/">{% trans 'Home' %}</a>
          </li>
          <li class="menu-item">
<!--            <span class="menu-label menu-label_danger">New</span>-->
            <a class="menu-link" href="{% url 'stores-polls:stores-list' %}">{% trans 'Shops' %}</a>
          </li>
          <li class="menu-item"><a class="menu-link" href="{% url 'discounts-polls:discounts-list' %}">{% trans 'Promotions' %}</a>
          </li>
<!--          <li class="menu-item"><span class="menu-label menu-label_success">{% trans 'Hot' %}</span><a class="menu-link" href="#">{% trans 'Gallery' %}</a>-->
<!--          </li>-->
          <li class="menu-item"><a class="menu-link" href="#">{% trans 'Contacts' %}</a>
          </li>
          <li class="menu-item"><a class="menu-link" href="{% url 'goods-polls:catalog_url' %}">{% trans 'Purchase' %}</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="row-block">
      <div class="CartBlock">
          <a class="CartBlock-block" href="{% url 'orders-polls:compare' %}"><img class="CartBlock-img" src="{% static 'assets/img/icons/exchange.svg' %}" alt="exchange.svg"/><span class="CartBlock-amount">{{ total_compared }}</span></a>
          <a class="CartBlock-block" href="{% url 'orders-polls:cart_detail' %}"><img class="CartBlock-img" src="{% static 'assets/img/icons/cart.svg' %}" alt="cart.svg"/><span class="CartBlock-amount">{{ cart|length }}</span></a>
        <div class="CartBlock-block"><span class="CartBlock-price">{{ cart.get_total_sum }}$</span>
        </div>
      </div>
    </div>
    <div class="row-block Header-trigger"><a class="menuTrigger" href="#navigate">
        <div class="menuTrigger-content">{% trans 'Show navigation' %}
        </div><span></span><span></span><span></span></a>
    </div>
  </div>
</div>

templates/elems/random_categories.html
{% load static %}
{% load i18n %}

  <div class="Section">
    <div class="wrap">
      <div class="BannersHome">
          {% for category in random_categories %}
          <a class="BannersHomeBlock" href="{% url 'goods-polls:catalog_url' %}?slug={{category.slug}}">
            <div class="BannersHomeBlock-row">
            <div class="BannersHomeBlock-block">
              <strong class="BannersHomeBlock-title">{% if category.parent %}{{ category.parent }} / {% endif %}{{ category.name }}
              </strong>
              <div class="BannersHomeBlock-content">{% trans 'from' %}&#32;<span class="BannersHomeBlock-price">${{ category.from_price }}</span>
              </div>
            </div>
            <div class="BannersHomeBlock-block">
              <div class="BannersHomeBlock-img">
                <img src="{{ category.image_url }}" alt="card.jpg"/>
              </div>
            </div>
          </div>
          </a>
          {% endfor %}
      </div>
    </div>
  </div>

templates/elems/special_product.html
{% load static %}
{% load i18n %}

  <div class="Section-column">
    <div class="Section-columnSection Section-columnSection_mark">
      <header class="Section-columnHeader">
        <strong class="Section-columnTitle">{%  trans 'Limited Deals' %}
        </strong>
      </header>
      <div class="Card">
        <div class="store-name">
            <a href="{% url 'stores-polls:store-detail' special_product.seller.slug %}"><img src="{{special_product.seller.icon_url}}" alt="store-icon"></a>
        </div>
        <form method="get" action="{% url 'orders-polls:add_viewed' %}">
          <input type="hidden" name="seller_product_id" value="{{ special_product.id }}">
          <button class="Card-picture" type="submit"><img src="{{ special_product.product.image_url }}" alt="card.jpg"/></button>
        <div class="Card-content">
          <button class="Card-title" type="submit">{{ special_product.product.name }}
          </button>
          <div class="Card-description">
            <div class="Card-cost">
                <span class="Card-priceOld">{% if special_discount_price and not special_discount.set_discount %}${{ special_product.price }}{% endif %}</span>
                <span class="Card-price">
                    {% if special_discount_price and not special_discount.set_discount %}
                        ${{ special_discount_price|floatformat:0 }}
                    {% else %}
                        ${{ special_product.price }}
                    {% endif %}
                </span>
            </div>
            <div class="Card-category">{% if special_product.product.category.parent %}{{ special_product.product.category.parent }} / {% endif %}{{ special_product.product.category }}
            </div>
          </div>
          <div class="CountDown" data-date="{{ update_time }}">
            <div class="CountDown-block">
              <div class="CountDown-wrap">
                <div class="CountDown-days">
                </div><span class="CountDown-label">{% trans 'days' %}</span>
              </div>
            </div>
            <div class="CountDown-block">
              <div class="CountDown-wrap">
                <div class="CountDown-hours">
                </div><span class="CountDown-label">{% trans 'hours' %}</span>
              </div>
            </div>
            <div class="CountDown-block">
              <div class="CountDown-wrap">
                <div class="CountDown-minutes">
                </div><span class="CountDown-label">{% trans 'mins' %}</span>
              </div>
            </div>
            <div class="CountDown-block">
              <div class="CountDown-wrap">
                <div class="CountDown-secs">
                </div><span class="CountDown-label">{% trans 'secs' %}</span>
              </div>
            </div>
          </div>
        </div>
        </form>
      </div>
    </div>
  </div>