config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from settings_app.views import AdminView
from settings_app.language import set_language

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="MEGANO payment API",
        default_version="v1",
        description="This api is used for getting payments through random account",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="megano@megano.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("i18n", set_language, name="set_language"),
    path("admin/", admin.site.urls),
    path("admin/", include("admin_tools.urls")),
    path("api_auth/", include("rest_framework.urls")),
    path("api/", include("payments_app.urls")),
    path("settings-admin/", include("settings_app.urls", namespace="settings-polls")),
    path("", include("goods_app.urls", namespace="goods-polls")),
    path("users/", include("profiles_app.urls", namespace="profiles-polls")),
    path("accounts/", include("allauth.urls")),
    path("orders/", include("orders_app.urls", namespace="orders-polls")),
    path("stores/", include("stores_app.urls", namespace="stores-polls")),
    path("discounts/", include("discounts_app.urls", namespace="discounts-polls")),
    path("swagger/", schema_view.with_ui("swagger", cache_timeout=0), name="schema-swagger-ui"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goods_app/urls.py
from django.urls import path
from goods_app.views import IndexView, ProductDetailView, get_reviews, post_review, FullCatalogView, AllCardForAjax

app_name = "goods"
urlpatterns = [
    path("", IndexView.as_view(), name="index_url"),
    path("product-detail/<str:slug>/", ProductDetailView.as_view(), name="product-detail"),
    path("get_reviews/", get_reviews, name="get_reviews"),
    path("post_review/", post_review, name="post_review"),
    path("catalogs/", FullCatalogView.as_view(), name="catalog_url"),
    path("async_catalog/", AllCardForAjax.as_view(), name="ajax_full"),
]

orders_app/urls.py
from django.urls import path
from orders_app import views

app_name = "orders"
urlpatterns = [
    # эндпоинты корзины
    path("cart/", views.CartView.as_view(), name="cart_detail"),
    path("cart/<int:product_id>", views.CartView.as_view(), name="cart_detail_post"),
    path("add/<int:product_id>/", views.CartAdd.as_view(), name="cart_add"),
    path("add/<int:product_id>/", views.CartAdd.as_view(), name="cart_add_many"),
    path("remove/<int:product_id>/", views.CartRemove.as_view(), name="cart_remove"),
    path("clear/", views.cart_clear, name="cart_clear"),
    # эндпоинты оформления заказа
    path("step1/", views.OrderStepOne.as_view(), name="order_step_one"),
    path("step11/", views.OrderStepOneAnonym.as_view(), name="order_step_one_anonymous"),
    path("step2/", views.OrderStepTwo.as_view(), name="order_step_two"),
    path("step3/", views.OrderStepThree.as_view(), name="order_step_three"),
    path("step4/", views.OrderStepFour.as_view(), name="order_step_four"),
    # эндпоинты оплаты
    path("payment/<int:order_id>", views.PaymentView.as_view(), name="payment"),
    path("payment/card/<int:order_id>", views.PaymentWithCardView.as_view(), name="payment_with_card"),
    path("payment/account/<int:order_id>", views.PaymentWithAccountView.as_view(), name="payment_with_account"),
    path("done/", views.payment_done, name="payment_done"),
    path("canceled/", views.payment_canceled, name="payment_canceled"),
    # эндпоинты товаров для сравнения
    path("compare/", views.CompareView.as_view(), name="compare"),
    path("compare/add/<int:product_id>/", views.AddToCompare.as_view(), name="add-to-compare"),
    path("compare/remove/<str:product_name>/", views.RemoveFromCompare.as_view(), name="remove-from-compare"),
    # эндпоинты истории заказов
    path("history/", views.HistoryOrderView.as_view(), name="history-order"),
    path("history/<int:order_id>", views.HistoryOrderDetail.as_view(), name="history-order-detail"),
    # эндроинты истории просмотров
    path("viewed_history/", views.ViewedGoodsView.as_view(), name="history-view"),
    path("add_viewed/", views.add_viewed, name="add_viewed"),
]

profiles_app/urls.py
from django.urls import path
from profiles_app.views import UserLogin, UserLogout, RegisterView, RestorePasswordView, AccountView, AccountEditView

app_name = "profiles"
urlpatterns = [
    path("login/", UserLogin.as_view(), name="login"),
    path("logout/", UserLogout.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("restore-password/", RestorePasswordView.as_view(), name="restore-password"),
    path("private-room/", AccountView.as_view(), name="private-room"),
    path("private-room/profile/", AccountEditView.as_view(), name="account-edit"),
]

stores_app/urls.py
from django.urls import path
from stores_app import views


app_name = "stores"
urlpatterns = [
    path("add-store/", views.AddNewStoreView.as_view(), name="add-store"),
    path("add-store-product/", views.AddSellerProductView.as_view(), name="add-store-product"),
    path("sellers-room/", views.SellersRoomView.as_view(), name="sellers-room"),
    path("request-add-new-product/", views.RequestNewProduct.as_view(), name="request-new-product"),
    path("category-filter/", views.CategoryFilter.as_view(), name="category-filter"),
    path("delete-store/", views.remove_Store, name="delete-store"),
    path("delete-seller-product/", views.remove_SellerProduct, name="delete-seller-product"),
    path("edit-store/<str:slug>/", views.EditStoreView.as_view(), name="edit-store"),
    path("stores-list/", views.StoresListView.as_view(), name="stores-list"),
    path("products-list/", views.AllSellerProductView.as_view(), name="all-products-list"),
    path("store-detail/<str:slug>/", views.StoreDetailView.as_view(), name="store-detail"),
    path("<str:slug>/<int:pk>/", views.EditSelleProductView.as_view(), name="edit-seller-product"),
    # discount endpoints
    path("add-store-product-discount/", views.AddProductDiscountView.as_view(), name="add-store-product-discount"),
    path("delete-store-product-discount/", views.remove_ProductDiscount, name="delete-store-product-discount"),
    path(
        "edit-store-product-discount/<str:slug>/<int:pk>/",
        views.EditProductDiscountView.as_view(),
        name="edit-store-product-discount",
    ),
    path("add-store-group-discount/", views.AddGroupDiscountView.as_view(), name="add-store-group-discount"),
    path("delete-store-group-discount/", views.remove_GroupDiscount, name="delete-store-group-discount"),
    path(
        "edit-store-group-discount/<str:slug>/<int:pk>/",
        views.EditGroupDiscountView.as_view(),
        name="edit-store-group-discount",
    ),
    path("add-store-cart-discount/", views.AddCartDiscountView.as_view(), name="add-store-cart-discount"),
    path("delete-store-cart-discount/", views.remove_CartDiscount, name="delete-store-cart-discount"),
    path(
        "edit-store-cart-discount/<str:slug>/<int:pk>/",
        views.EditCartDiscountView.as_view(),
        name="edit-store-cart-discount",
    ),
    path("import/", views.ImportView.as_view(), name="import"),
]

goods_app/models.py
from typing import Callable

from django.urls import reverse
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext_lazy as _

from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel
from taggit.managers import TaggableManager

User = get_user_model()


class ProductCategory(MPTTModel):
    """
    Модель категории товаров
    """

    name = models.CharField(max_length=25, null=True, verbose_name=_("category title"))
    slug = models.SlugField(verbose_name=_("slug"), unique=True)
    description = models.TextField(max_length=255, null=True, blank=True, verbose_name=_("description"))
    parent = TreeForeignKey("self", on_delete=models.CASCADE, null=True, blank=True, related_name="children")
    icon = models.ImageField(verbose_name=_("icon"))
    image = models.ImageField(verbose_name=_("image"))

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name_plural = _("product categories")
        verbose_name = _("product category")

    class MPTTMeta:
        order_insertion_by = ["name"]

    @property
    def image_url(self):
        if self.image and hasattr(self.image, "url"):
            return self.image.url

    @property
    def icon_url(self):
        if self.icon and hasattr(self.icon, "url"):
            return self.icon.url

    def save(self, *args, **kwargs) -> Callable:
        """
        Method overridden to remove old files and add permissions
        """
        if self.pk is not None:
            old_self = ProductCategory.objects.get(pk=self.pk)
            if old_self.image and self.image != old_self.image:
                old_self.image.delete(False)
            if old_self.icon and self.icon != old_self.icon:
                old_self.icon.delete(False)
        return super(ProductCategory, self).save(*args, **kwargs)


class Product(models.Model):
    """
    Модель товара
    """

    category = models.ForeignKey(
        ProductCategory,
        on_delete=models.CASCADE,
        related_name="products",
        verbose_name="good_category",
    )
    name = models.CharField(max_length=100, verbose_name=_("product name"))
    code = models.CharField(max_length=10, null=True, blank=True, verbose_name=_("product code"))
    slug = models.SlugField(db_index=True, verbose_name=_("product slug"), unique=True)
    image = models.ImageField(verbose_name=_("product image"))
    description = models.TextField(max_length=2550, null=True, verbose_name=_("product description"))
    rating = models.FloatField(null=True, default=0, verbose_name=_("rating"))
    is_published = models.BooleanField(verbose_name=_("is published"), null=True, blank=True, default=True)
    tags = TaggableManager()
    limited = models.BooleanField(default=False, verbose_name=_("limited edition"))

    def __str__(self):
        return self.name

    def get_absolute_url(self) -> Callable:
        return reverse("goods-polls:product-detail", kwargs={"slug": self.slug})

    @property
    def image_url(self):
        if self.image and hasattr(self.image, "url"):
            return self.image.url

    class Meta:
        verbose_name = _("product")
        verbose_name_plural = _("products")
        db_table = "products"

    def save(self, *args, **kwargs) -> Callable:
        """
        Method overridden to remove old files and add permissions
        """
        if self.pk is not None:
            old_self = Product.objects.get(pk=self.pk)
            if old_self.image and self.image != old_self.image:
                old_self.image.delete(False)
        return super().save(*args, **kwargs)


class ProductComment(models.Model):
    """
    Модель комментария к товару
    """

    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="product_comments")
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    author = models.CharField(verbose_name=_("author"), max_length=25, null=True)
    content = models.TextField(verbose_name=_("content"), max_length=255, null=True)
    added = models.DateTimeField(verbose_name=_("added"), auto_now_add=True, null=True)
    rating = models.IntegerField(verbose_name=_("rating"))

    def __str__(self) -> str:
        return f"Comments for {str(self.product)}"

    class Meta:
        verbose_name = _("product comment")
        verbose_name_plural = _("product comments")
        db_table = "comments"


class SpecificationsNames(models.Model):
    """Все возможные характеристики"""

    name = models.CharField(max_length=32)

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = _("specification name")
        verbose_name_plural = _("specification names")
        db_table = "specification_names"


class Specifications(models.Model):
    """Модель Характеристики товара"""

    value = models.CharField(max_length=32, null=False)
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, blank=True, null=True, related_name="specifications"
    )
    current_specification = models.ForeignKey(
        SpecificationsNames, on_delete=models.CASCADE, blank=True, null=True, related_name="specifications"
    )

    def __str__(self) -> str:
        return self.value

    class Meta:
        verbose_name = _("specification")
        verbose_name_plural = _("specifications")
        db_table = "specifications"


class ProductRequest(Product):
    """
    Model for requesting to add new Product
    """

    product_ptr = models.OneToOneField(Product, on_delete=models.DO_NOTHING, parent_link=True, primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    store = models.CharField(verbose_name=_("store"), max_length=30)
    notes = models.TextField(verbose_name=_("notes"), max_length=255, null=True, blank=True)

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = _("new product")
        verbose_name_plural = _("new products")
        db_table = "add_products"

stores_app/models.py
import os
from typing import Callable, Dict

from django.contrib.auth import get_user_model
from django.db.models import QuerySet
from django.utils.translation import gettext_lazy as _
from django.db import models
from django.urls import reverse

from goods_app.models import Product
from settings_app.utils import check_image_size

User = get_user_model()


class Seller(models.Model):
    """
    Store model
    """

    name = models.CharField(max_length=50, verbose_name=_("name"))
    slug = models.SlugField(verbose_name="slug", unique=True)
    description = models.TextField(max_length=2550, null=True, blank=True, default="", verbose_name=_("description"))
    address = models.TextField(max_length=100, null=True, blank=True, default="", verbose_name=_("address"))
    icon = models.ImageField(upload_to="icons/", null=True, verbose_name=_("icon"))
    email = models.EmailField(null=True, blank=True, default="", verbose_name="email")
    phone = models.CharField(max_length=16, null=True, blank=True, default="", verbose_name=_("phone"))
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="seller", verbose_name=_("owner"))

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self) -> Callable:
        return reverse("stores-polls:store-detail", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs) -> None:
        check_image_size(self.icon)
        if self.pk is not None:
            old_self = Seller.objects.get(pk=self.pk)
            if old_self.icon and self.icon != old_self.icon:
                old_self.icon.delete(False)
        super(Seller, self).save(*args, **kwargs)

    @property
    def icon_url(self):
        if self.icon and hasattr(self.icon, "url"):
            return self.icon.url

    class Meta:
        verbose_name = _("store")
        verbose_name_plural = _("stores")
        db_table = "sellers"


class SellerProduct(models.Model):
    """
    Seller product model
    """

    seller = models.ForeignKey(
        Seller, on_delete=models.CASCADE, related_name="seller_products", verbose_name=_("seller")
    )
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="seller_products", verbose_name=_("product")
    )
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name=_("price"))
    quantity = models.IntegerField(verbose_name=_("quantity"))
    date_added = models.DateTimeField(verbose_name=_("date added"), auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.product} in {self.seller}"

    def serialize(self) -> Dict:
        return self.__dict__

    class Meta:
        verbose_name = _("product in shop")
        verbose_name_plural = _("products in shop")
        db_table = "store_products"

    def get_absolute_url(self) -> Callable:
        return reverse("stores-polls:edit-seller-product", kwargs={"slug": self.seller.slug, "pk": self.id})

    # Pay attention to discounts
    @property
    def get_discount(self) -> QuerySet:
        """
        Get all related ProductDiscounts
        """
        return self.product_discounts.all()


class ProductImportFile(models.Model):
    """Модель файла импорта товаров"""

    file = models.FileField(upload_to="import/products")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="import_files")
    errors = models.IntegerField(default=0)
    warnings = models.IntegerField(default=0)
    log_info = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now=True)
    status = models.CharField(default="In progress", blank=True, max_length=24)

    def filename(self):
        return os.path.basename(self.file.name)


class ImportOrder(models.Model):
    can_import = models.BooleanField(default=True)

templates/stores_app/edit-store.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load account socialaccount %}

{% block title %}{% trans 'Sellers Room' %}
{% endblock %}

{% block header %}
{% include 'elems/header.html' %}
{% endblock %}

{% block main %}
<div class="Middle Middle_top">
    <div class="Middle-top">
        <div class="wrap">
            <div class="Middle-header">
                <h1 class="Middle-title">{{ store.name }}</h1>
                <ul class="breadcrumbs Middle-breadcrumbs">
                    <li class="breadcrumbs-item"><a href="/">{% trans 'home' %}</a></li>
                    <li class="breadcrumbs-item breadcrumbs-item_current"><span>{% trans 'Store Detail' %}</span></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="Section Section_column Section_columnLeft">
        <div class="wrap">
            <div class="Section-column">
                <div class="Section-columnSection">
                    <header class="Section-header">
                      <strong class="Section-title">{% trans 'Navigation' %}
                      </strong>
                    </header>
                    <div class="Section-columnContent">
                        <div class="NavigateProfile">
                            <ul class="menu menu_vt">
                                <li class="menu-item"><a class="menu-link" href="{% url 'profiles-polls:private-room' %}">{% trans 'Account info' %}</a>
                                </li>
                                <li class="menu-item"><a class="menu-link" href="{% url 'profiles-polls:account-edit' %}">{% trans 'Profile' %}</a>
                                </li>
                          <li class="menu-item"><a class="menu-link" href="{% url 'orders-polls:history-order' %}">{% trans 'Orders history' %}</a>
                                </li>
                                <li class="menu-item"><a class="menu-link" href="{% url 'orders-polls:history-view' %}">{% trans 'Views history' %}</a>
                                </li>
                                {% if perms.profiles_app.Sellers %}
                                <li class="menu-item_ACTIVE menu-item"><a class="menu-link" href="{% url 'stores-polls:sellers-room' %}">{% trans 'Sellers room' %}</a>
                                </li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="Section-content">
              <div class="Profile">
                  <form class="form Profile-form" method="post" enctype="multipart/form-data">
                      {% csrf_token %}
                      <div class="row">
                         <div class="row-block">
                             <div class="form-group require-field">
                                 <label class="form-label" for="id_name">{% trans 'Store name' %}</label>
                                 <input class="form-input" id="id_name" required name="name" value="{{store.name}}" type="text">
                                 <span class="formerror">{{form.errors.name}}</span>
                             </div>
                             <div class="form-group require-field">
                                 <label class="form-label" for="id_email">{% trans 'Email' %}</label>
                                 <input class="form-input" id="id_email" name="email" value="{{store.email}}" type="email">
                                 <span class="formerror">{{form.errors.email}}</span>
                             </div>
                             <div class="form-group">
                                 <label class="form-label" for="id_description">{% trans 'Description' %}</label>
                                 <textarea class="form-area" name="description" cols="10" rows="13" maxlength="255" id="id_description"></textarea>
                                 <span class="formerror">{{form.errors.description}}</span>
                             </div>
                         </div>
                         <div class="row-block">
                             <div class="form-group require-field">
                                 <label class="form-label" for="id_slug">{% trans 'URL-name' %}</label>
                                 <input class="form-input" id="id_slug" name="slug" value="{{store.slug}}" disabled type="text">
                                 <span class="formerror">{{form.errors.slug}}</span>
                            </div>
                             <div class="form-group require-field">
                                 <label class="form-label" for="id_phone">{% trans 'Phone Number' %}</label>
                                 <input class="form-input" id="id_phone" name="phone" value="{{store.phone}}" type="text">
                                 <span class="formerror">{{form.errors.phone}}</span>
                             </div>
                             <div class="form-group">
                                 <label class="form-label" for="id_address">{% trans 'Address' %}</label>
                                 <textarea class="form-area" name="address" cols="10" rows="4" maxlength="255" id="id_address"></textarea>
                                 <span class="formerror">{{form.errors.address}}</span>
                             </div>
                             <div class="form-group">
                                <label class="form-label" for="avatar">{% trans 'Store logo' %}
                                </label>
                                {% if store.icon %}
                                <div class="Profile-avatar" style="height: 175px;">
                                {% else %}
                                <div class="Profile-avatar Profile-avatar_noimg" style="height: 175px;">
                                {% endif %}
                                     <div class="Profile-img">
                                     {% if store.icon %}
                                        <img src="{{ store.icon_url }}" alt="#.png"/>
                                     {% else %}
                                         <img src="assets/img/#.png" alt="#.png">
                                     {% endif %}
                                     </div>
                                     <span class="avatar-span">{% trans 'Click on picture for change' %}</span>
                                     <label class="Profile-fileLabel" for="avatar">{% trans 'Choose logo'  %}
                                     </label>
                                     <input class="Profile-file form-input" id="avatar" name="icon" type="file" data-validate="onlyImgAvatar"/>
                                </div>
                                <span class="formerror">{{form.errors.icon}}</span>
                             </div>
                             <div class="form-group">
                                 <div class="Profile-btn  custom_align-center">
                                     <a class="btn btn_success" href="{% url 'stores-polls:sellers-room' %}">Back to seller room</a>
                                     <button class="btn btn_success" type="submit">{% trans 'Save changes' %}</button>
                                     <div class="Profile-success">{{form.non_field_errors}}</div>
                                 </div>
                             </div>
                         </div>
                     </div>
                 </form>
             </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block footer %}
{% include 'elems/footer.html' %}
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script src="{% static 'assets/js/main.js' %}"></script>
{% endblock %}

templates/stores_app/new_product_in_store.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block title %}{% trans 'Add Product in Store' %}
{% endblock %}


{% block top_scripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/hogan.js/3.0.2/hogan.js"></script>
{% endblock %}

{% block header %}
{% include 'elems/header.html' %}
{% endblock %}

{% block main %}
<div class="Middle-top">
    <div class="wrap">
        <div class="Middle-header">
            <h1 class="Middle-title">{% trans 'Add Product in Store' %}</h1>
            <ul class="breadcrumbs Middle-breadcrumbs">
                <li class="breadcrumbs-item"><a href="/">{% trans 'home' %}</a></li>
                <li class="breadcrumbs-item breadcrumbs-item_current"><span>{% trans 'Sellers Room' %}</span></li>
            </ul>
        </div>
    </div>
</div>
<div class="Section Section_column Section_columnLeft">
  <div class="wrap">
      <div class="Section-column">
          <div class="Section-columnSection">
              <header class="Section-header">
                  <strong class="Section-title">{% trans 'Navigation' %}
                  </strong>
              </header>
              <div class="Section-columnContent">
                  <div class="NavigateProfile">
                      <ul class="menu menu_vt">
                          <li class="menu-item"><a class="menu-link" href="{% url 'profiles-polls:private-room' %}">{% trans 'Account info' %}</a>
                          </li>
                          <li class="menu-item"><a class="menu-link" href="{% url 'profiles-polls:account-edit' %}">{% trans 'Profile' %}</a>
                          </li>
                          <li class="menu-item"><a class="menu-link" href="{% url 'orders-polls:history-order' %}">{% trans 'Orders history' %}</a>
                          </li>
                          <li class="menu-item"><a class="menu-link" href="{% url 'orders-polls:history-view' %}">{% trans 'Viewed products' %}</a>
                          </li>
                          <li class="menu-item_ACTIVE menu-item"><a class="menu-link" href="{% url 'stores-polls:sellers-room' %}">{% trans 'Sellers room' %}</a>
                          </li>
                      </ul>
                  </div>
              </div>
          </div>
      </div>
      <div class="Section-content">
          <div class="Profile">
              <form class="category-form" name="category-filter" id="id_add_product" method="GET" action="{% url 'stores-polls:category-filter' %}">
                    <label class="form-label" style ="font-size: 20px;" for="id_category">{% trans 'Choose Category Product' %}:</label>
                    <select class="form-area" name="category_id" required="" id="id_category">
                        <option value="" selected="">---------</option>
                        {% for category in categories %}
                        <option value="{{ category.id }}">{{ category.name|capfirst }}</option>
                        {%  endfor %}
                    </select>
              </form>
              <form class="form Profile-form" method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                  <div class="row flex column-direction">
                      <div class="row-block">
                          <div class="form-group require-field product_js"></div>
                          <div class="form-group require-field">
                              <label class="form-label" for="id_seller">{% trans 'Choose store' %}</label>
                              <select class="form-area" name="seller" required="" id="id_seller">
                                  <option value="" selected="">---------</option>
                                  {% for store in stores %}
                                  <option value="{{ store.id }}">{{ store.name }}</option>
                                  {% endfor %}
                              </select>
                              <span class="formerror">{{form.errors.seller}}</span>
                          </div>

                      </div>
                  </div>
                  <div class="row flex block-input-numbers">
                      <div class="row-block">
                          <div class="form-group reset-margin require-field">
                              <label class="form-label" for="id_quantity">{% trans 'Quantity' %}:
                              </label>
                              <input class="form-input" type="number" name="quantity" required id="id_quantity">
                          </div>
                      </div>
                      <div class="row-block">
                          <div class="form-group require-field">
                              <label class="form-label" for="id_price">{% trans 'Price' %}:</label>
                              <input class="form-input" id="id_price" name="price" type="number" required step="1.00">
                              <span class="formerror">{{form.errors.price}}</span>
                          </div>
                      </div>
                  </div>
                  <div class="row-block flex custom_register_name-block">
                      <div class="form-group custom_login_form-group-btns">
                          <div class="Profile-btn custom_align-center custom_margin-bottom">
                              <a class="btn btn_success" href="{% url 'stores-polls:sellers-room' %}">{%  trans 'Back to seller room' %}</a>
                              <button class="btn btn_success" type="submit">{% trans 'Add product' %}</button>
                              <a href="{% url 'stores-polls:request-new-product' %}" class="btn btn_success">Request for new product</a>
                          </div>
                      </div>
                  </div>
              </form>
          </div>
          {% if messages %}
            {% for message in messages %}
                {% if message.level == CREATE_PRODUCT_ERROR %}
                <div style="position: absolute; color: red; top:500px;">{{message}}</div>
                {% endif %}
            {%endfor %}
          {% endif %}
      </div>
  </div>
</div>

{% endblock %}

{% block footer %}
{% include 'elems/footer.html' %}
{% endblock %}

{% block scripts %}
    <script src="{% static 'assets/js/main.js' %}"></script>
{% endblock %}