config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from settings_app.views import AdminView
from settings_app.language import set_language

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="MEGANO payment API",
        default_version="v1",
        description="This api is used for getting payments through random account",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="megano@megano.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("i18n", set_language, name="set_language"),
    path("admin/", admin.site.urls),
    path("admin/", include("admin_tools.urls")),
    path("api_auth/", include("rest_framework.urls")),
    path("api/", include("payments_app.urls")),
    path("settings-admin/", include("settings_app.urls", namespace="settings-polls")),
    path("", include("goods_app.urls", namespace="goods-polls")),
    path("users/", include("profiles_app.urls", namespace="profiles-polls")),
    path("accounts/", include("allauth.urls")),
    path("orders/", include("orders_app.urls", namespace="orders-polls")),
    path("stores/", include("stores_app.urls", namespace="stores-polls")),
    path("discounts/", include("discounts_app.urls", namespace="discounts-polls")),
    path("swagger/", schema_view.with_ui("swagger", cache_timeout=0), name="schema-swagger-ui"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goods_app/urls.py
from django.urls import path
from goods_app.views import IndexView, ProductDetailView, get_reviews, post_review, FullCatalogView, AllCardForAjax

app_name = "goods"
urlpatterns = [
    path("", IndexView.as_view(), name="index_url"),
    path("product-detail/<str:slug>/", ProductDetailView.as_view(), name="product-detail"),
    path("get_reviews/", get_reviews, name="get_reviews"),
    path("post_review/", post_review, name="post_review"),
    path("catalogs/", FullCatalogView.as_view(), name="catalog_url"),
    path("async_catalog/", AllCardForAjax.as_view(), name="ajax_full"),
]

orders_app/urls.py
from django.urls import path
from orders_app import views

app_name = "orders"
urlpatterns = [
    # эндпоинты корзины
    path("cart/", views.CartView.as_view(), name="cart_detail"),
    path("cart/<int:product_id>", views.CartView.as_view(), name="cart_detail_post"),
    path("add/<int:product_id>/", views.CartAdd.as_view(), name="cart_add"),
    path("add/<int:product_id>/", views.CartAdd.as_view(), name="cart_add_many"),
    path("remove/<int:product_id>/", views.CartRemove.as_view(), name="cart_remove"),
    path("clear/", views.cart_clear, name="cart_clear"),
    # эндпоинты оформления заказа
    path("step1/", views.OrderStepOne.as_view(), name="order_step_one"),
    path("step11/", views.OrderStepOneAnonym.as_view(), name="order_step_one_anonymous"),
    path("step2/", views.OrderStepTwo.as_view(), name="order_step_two"),
    path("step3/", views.OrderStepThree.as_view(), name="order_step_three"),
    path("step4/", views.OrderStepFour.as_view(), name="order_step_four"),
    # эндпоинты оплаты
    path("payment/<int:order_id>", views.PaymentView.as_view(), name="payment"),
    path("payment/card/<int:order_id>", views.PaymentWithCardView.as_view(), name="payment_with_card"),
    path("payment/account/<int:order_id>", views.PaymentWithAccountView.as_view(), name="payment_with_account"),
    path("done/", views.payment_done, name="payment_done"),
    path("canceled/", views.payment_canceled, name="payment_canceled"),
    # эндпоинты товаров для сравнения
    path("compare/", views.CompareView.as_view(), name="compare"),
    path("compare/add/<int:product_id>/", views.AddToCompare.as_view(), name="add-to-compare"),
    path("compare/remove/<str:product_name>/", views.RemoveFromCompare.as_view(), name="remove-from-compare"),
    # эндпоинты истории заказов
    path("history/", views.HistoryOrderView.as_view(), name="history-order"),
    path("history/<int:order_id>", views.HistoryOrderDetail.as_view(), name="history-order-detail"),
    # эндроинты истории просмотров
    path("viewed_history/", views.ViewedGoodsView.as_view(), name="history-view"),
    path("add_viewed/", views.add_viewed, name="add_viewed"),
]

profiles_app/urls.py
from django.urls import path
from profiles_app.views import UserLogin, UserLogout, RegisterView, RestorePasswordView, AccountView, AccountEditView

app_name = "profiles"
urlpatterns = [
    path("login/", UserLogin.as_view(), name="login"),
    path("logout/", UserLogout.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("restore-password/", RestorePasswordView.as_view(), name="restore-password"),
    path("private-room/", AccountView.as_view(), name="private-room"),
    path("private-room/profile/", AccountEditView.as_view(), name="account-edit"),
]

stores_app/urls.py
from django.urls import path
from stores_app import views


app_name = "stores"
urlpatterns = [
    path("add-store/", views.AddNewStoreView.as_view(), name="add-store"),
    path("add-store-product/", views.AddSellerProductView.as_view(), name="add-store-product"),
    path("sellers-room/", views.SellersRoomView.as_view(), name="sellers-room"),
    path("request-add-new-product/", views.RequestNewProduct.as_view(), name="request-new-product"),
    path("category-filter/", views.CategoryFilter.as_view(), name="category-filter"),
    path("delete-store/", views.remove_Store, name="delete-store"),
    path("delete-seller-product/", views.remove_SellerProduct, name="delete-seller-product"),
    path("edit-store/<str:slug>/", views.EditStoreView.as_view(), name="edit-store"),
    path("stores-list/", views.StoresListView.as_view(), name="stores-list"),
    path("products-list/", views.AllSellerProductView.as_view(), name="all-products-list"),
    path("store-detail/<str:slug>/", views.StoreDetailView.as_view(), name="store-detail"),
    path("<str:slug>/<int:pk>/", views.EditSelleProductView.as_view(), name="edit-seller-product"),
    # discount endpoints
    path("add-store-product-discount/", views.AddProductDiscountView.as_view(), name="add-store-product-discount"),
    path("delete-store-product-discount/", views.remove_ProductDiscount, name="delete-store-product-discount"),
    path(
        "edit-store-product-discount/<str:slug>/<int:pk>/",
        views.EditProductDiscountView.as_view(),
        name="edit-store-product-discount",
    ),
    path("add-store-group-discount/", views.AddGroupDiscountView.as_view(), name="add-store-group-discount"),
    path("delete-store-group-discount/", views.remove_GroupDiscount, name="delete-store-group-discount"),
    path(
        "edit-store-group-discount/<str:slug>/<int:pk>/",
        views.EditGroupDiscountView.as_view(),
        name="edit-store-group-discount",
    ),
    path("add-store-cart-discount/", views.AddCartDiscountView.as_view(), name="add-store-cart-discount"),
    path("delete-store-cart-discount/", views.remove_CartDiscount, name="delete-store-cart-discount"),
    path(
        "edit-store-cart-discount/<str:slug>/<int:pk>/",
        views.EditCartDiscountView.as_view(),
        name="edit-store-cart-discount",
    ),
    path("import/", views.ImportView.as_view(), name="import"),
]

orders_app/models.py
from decimal import Decimal
from django.core.validators import RegexValidator
from django.db import models
from stores_app.models import SellerProduct
from profiles_app.models import User
from django.utils.translation import gettext_lazy as _


class Order(models.Model):
    """
    Модель заказа
    """

    DELIVERY_CHOICES = [("reg", _("Regular")), ("exp", _("Express"))]

    PAYMENT_CHOICES = [
        ("card", _("Bank Card")),
        ("cash", _("From random account")),
    ]

    customer = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, related_name="orders", verbose_name=_("customer")
    )
    fio = models.CharField(max_length=100, null=True, blank=True, verbose_name=_("name and lastname"))

    phone_valid = RegexValidator(
        regex=r"^\+?1?\d{9,15}$",
        message=" ".join(
            [str(_("phone number must be entered in the format:")), "+999999999", str(_("up to 15 digits allowed."))]
        ),
    )
    phone = models.CharField(
        max_length=16, validators=[phone_valid], null=True, blank=True, verbose_name=_("phone number")
    )

    email = models.EmailField(null=True, blank=True, verbose_name=_("email"))

    delivery = models.CharField(max_length=3, choices=DELIVERY_CHOICES, default="reg", verbose_name=_("delivery"))

    payment_method = models.CharField(
        max_length=4, choices=PAYMENT_CHOICES, default="card", verbose_name=_("payment method")
    )

    city = models.CharField(max_length=25, null=True, blank=True, verbose_name=_("city"))
    address = models.TextField(max_length=255, null=True, blank=True, verbose_name=_("address"))

    in_order = models.BooleanField(default=False, verbose_name=_("in order"))
    paid = models.BooleanField(default=False, verbose_name=_("order is payed"))
    payment_error = models.CharField(max_length=50, null=True, blank=True, verbose_name=_("payment error"))

    ordered = models.DateTimeField(null=True, blank=True, verbose_name=_("order placement date"))
    braintree_id = models.CharField(max_length=150, blank=True, verbose_name=_("transaction id"))

    delivery_cost = models.DecimalField(max_digits=10, decimal_places=2, default=0, verbose_name=_("Delivery cost"))

    @property
    def total_sum(self) -> Decimal:
        """Метод получения общей стоимости товаров в заказе"""
        total = Decimal(0.00)
        for product in self.order_products.all():
            total += product.seller_product.price * product.quantity
        return Decimal(total)

    @property
    def total_discounted_sum(self) -> Decimal:
        """Метод получения общей стоимости товаров в заказе со скидками"""
        total = Decimal(0.00)
        for product in self.order_products.all():
            total += product.final_price * product.quantity
        return Decimal(total)

    @property
    def final_total(self):
        return self.total_discounted_sum + self.delivery_cost

    def __str__(self):
        return f'{_("Order")} №{self.id}'

    def name(self):
        return self.__str__()

    def __len__(self) -> int:
        """Метод получения количества товаров в заказе"""
        return len(self.order_products.all())

    class Meta:
        verbose_name = _("order")
        verbose_name_plural = _("orders")


class OrderProduct(models.Model):
    """
    Модель товара в заказе
    """

    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name="order_products")
    seller_product = models.ForeignKey(SellerProduct, on_delete=models.CASCADE, related_name="order_products")
    final_price = models.DecimalField(
        max_digits=10, decimal_places=2, default=0, verbose_name=_("Guess discount price")
    )
    quantity = models.IntegerField(null=True, default=1, verbose_name=_("quantity"))

    def __str__(self):
        return f"{_('OrderProduct')} №{self.id}"

    def name(self):
        return self.__str__()

    class Meta:
        verbose_name = _("order product")
        verbose_name_plural = _("order products")


class ViewedProduct(models.Model):
    """Модель просмотренного товара"""

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="viewed", blank=True, null=True)
    session = models.CharField(max_length=100, blank=True)
    product = models.ForeignKey("stores_app.SellerProduct", on_delete=models.CASCADE, related_name="viewed_list")
    date = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _("viewed product")
        verbose_name_plural = _("viewed products")

orders_app/forms.py
from django import forms
from orders_app.models import Order


class CartAddProductForm(forms.Form):
    """Form for adding product to cart"""

    quantity = forms.IntegerField(min_value=1)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)


class OrderStepOneForm(forms.ModelForm):
    """
    Order progress first step form. Adding name, surname, phone and email
    to order information.
    """

    class Meta:
        model = Order
        fields = ["fio", "phone", "email"]


class OrderStepTwoForm(forms.ModelForm):
    """
    Order progress second step form. Adding delivery type, city and address
    to order information.
    """

    class Meta:
        model = Order
        widgets = {
            "delivery": forms.RadioSelect(attrs={"class": "toggle-box"}),
            "address": forms.Textarea(attrs={"class": "form-textarea"}),
        }
        fields = ["delivery", "city", "address"]


class OrderStepThreeForm(forms.ModelForm):
    """
    Order progress third step form. Adding payment method
    to order information.
    """

    class Meta:
        model = Order
        widgets = {
            "payment_method": forms.RadioSelect(attrs={"class": "toggle-box"}),
        }
        fields = ["payment_method"]

templates/orders_app/historyorder.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block title %}
   {% trans 'Order history' %}
{% endblock %}
{%block header %}
   {% include 'elems/header.html' %}
{% endblock %}
{% block main %}
  <div class="Middle Middle_top">
    <div class="Middle-top">
      <div class="wrap">
        <div class="Middle-header">
          <h1 class="Middle-title">{% trans 'Orders history' %}
          </h1>
          <ul class="breadcrumbs Middle-breadcrumbs">
            <li class="breadcrumbs-item"><a href="index.html">home</a>
            </li>
            <li class="breadcrumbs-item breadcrumbs-item_current"><span>{% trans 'orders history' %}</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="Section Section_column Section_columnLeft">
      <div class="wrap">
        <div class="Section-column">
          <div class="Section-columnSection">
            <header class="Section-header">
              <strong class="Section-title">{% trans 'orders history' %}
              </strong>
            </header>
            <div class="Section-columnContent">
              <div class="NavigateProfile">
                <ul class="menu menu_vt">
                  <li class="menu-item"><a class="menu-link" href="{% url 'profiles-polls:private-room' %}">{% trans 'Account info' %}</a>
                  </li>
                  <li class="menu-item"><a class="menu-link" href="{% url 'profiles-polls:account-edit' %}">{% trans 'Profile' %}</a>
                  </li>
                  <li class="menu-item_ACTIVE menu-item"><a class="menu-link" href="{% url 'orders-polls:history-order' %}">{% trans 'Orders history' %}</a>
                  </li>
                  <li class="menu-item"><a class="menu-link" href="{% url 'orders-polls:history-view' %}">{% trans 'Views history' %}</a>
                  </li>
                  {% if perms.profiles_app.Sellers %}
                  <li class="menu-item"><a class="menu-link" href="{% url 'stores-polls:sellers-room' %}">{% trans 'Sellers room' %}</a>
                  </li>
                  {% endif %}
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="Section-content">
          <div class="Orders">
            {% for order in orders %}
            <!--Данные о заказах-->
            <div class="Order Order_anons">
              <div class="Order-personal">
                <div class="row">
                  <div class="row-block"><a class="Order-title" href="{{ order.id }}">{% trans 'Order' %}&#32;<span class="Order-numberOrder">{{ order.id }}</span>&#32;{% trans 'from' %}&#32;<span class="Order-dateOrder">{{ order.ordered }}</span></a>
                  </div>
                  <div class="row-block">
                    <div class="Order-info Order-info_delivery">
                      <div class="Order-infoType">{% trans 'Delivery' %}:
                      </div>
                      
                      <div class="Order-infoContent">
                        {% if order.delivery == 'reg' %}
                          {% trans 'Regular delivery' %}
                        {% else %}
                          {% trans 'Express delivery' %}
                        {% endif %}
                      </div>
                      
                    </div>
                    <div class="Order-info Order-info_pay">
                      <div class="Order-infoType">{% trans 'Payment' %}:
                      </div>
                      <div class="Order-infoContent">
                        {% if order.payment_method == 'card' %}
                          {% trans 'Card' %}
                        {% else %}
                          {% trans 'Random account' %}
                        {% endif %}
                      </div>
                    </div>
                    <div class="Order-info">
                      <div class="Order-infoType">{% trans 'Price' %}:
                      </div>
                      <div class="Order-infoContent"><span class="Order-price">{{ order.total_discounted_sum }}$</span><span class="Order-price_old">{{ order.total_sum }}$</span>
                      </div>
                    </div>
                    <div class="Order-info Order-info_status">
                      <div class="Order-infoType">{% trans 'Status' %}:
                      </div>
                      
                      <div class="Order-infoContent">
                        {% if order.paid %}
                        {% trans 'Paid' %}
                        {% else %}
                        {% trans 'Not paid' %}
                        {% endif %}
                      </div>
                      
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}
{% block footer %}
{% include 'elems/footer.html' %}
{% endblock %}

templates/orders_app/historyview.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load goods_tags %}

{% block title %}
   {% trans 'Viewed products' %}
{% endblock %}

{%block header %}
   {% include 'elems/header.html' %}
{% endblock %}

{% block main %}
  <div class="Middle Middle_top">
    <div class="Middle-top">
        <div class="wrap">
            <div class="Middle-header">
                <h1 class="Middle-title">{% trans 'Viewed products' %}</h1>
                <ul class="breadcrumbs Middle-breadcrumbs">
                    <li class="breadcrumbs-item"><a href="/">{% trans 'home' %}</a></li>
                    <li class="breadcrumbs-item breadcrumbs-item_current"><span>{% trans 'Viewed products' %}</span></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="Section Section_column Section_columnLeft">
      <div class="wrap">
        <div class="Section-column">
            <div class="Section-columnSection">
                <header class="Section-header">
                      <strong class="Section-title">{% trans 'Navigation' %}
                      </strong>
                </header>
                <div class="Section-columnContent">
                   <div class="NavigateProfile">
                        <ul class="menu menu_vt">
                            <li class="menu-item"><a class="menu-link" href="{% url 'profiles-polls:private-room' %}">{% trans 'Account info' %}</a>
                            </li>
                            <li class="menu-item"><a class="menu-link" href="{% url 'profiles-polls:account-edit' %}">{% trans 'Profile' %}</a>
                            </li>
                            <li class="menu-item"><a class="menu-link" href="{% url 'orders-polls:history-order' %}">{% trans 'Orders history' %}</a>
                            </li>
                            <li class="menu-item_ACTIVE menu-item"><a class="menu-link" href="{% url 'orders-polls:history-view' %}">{% trans 'Views history' %}</a>
                            </li>
                            {% if perms.profiles_app.Sellers %}
                            <li class="menu-item"><a class="menu-link" href="{% url 'stores-polls:sellers-room' %}">{% trans 'Sellers room' %}</a>
                            </li>
                            {% endif %}
                        </ul>
                   </div>
                </div>
            </div>
        </div>
        <div class="Section-content">
          <div class="Cards">
              {% cards goods %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block footer %}
  {% include 'elems/footer.html' %}
{% endblock %}

templates/orders_app/order_step_one.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}
  {% trans 'Order step 1' %}
{% endblock %}

{%block header %}
  {% include 'elems/header.html' %}
{% endblock %}
{%block main %}
  <div class="Middle Middle_top">
    <div class="Middle-top">
      <div class="wrap">
        <div class="Middle-header">
          <h1 class="Middle-title">{% trans 'Order checkout' %}
          </h1>
          <ul class="breadcrumbs Middle-breadcrumbs">
            <li class="breadcrumbs-item"><a href="/">home</a>
            </li>
            <li class="breadcrumbs-item breadcrumbs-item_current"><span>{% trans 'Order checkout' %}</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="Middle Middle_top">

    <div class="Section Section_column Section_columnRight Section_columnWide Order">
      <div class="wrap">
        <div class="Section-column">
          <div class="Section-columnSection">
            <header class="Section-header">
              <strong class="Section-title">{% trans 'Overall progress' %}
              </strong>
            </header>
            <div class="Section-columnContent">
              <ul class="menu menu_vt Order-navigate">
                <li class="menu-item_ACTIVE menu-item">
                    <a class="menu-link" href="{% url 'orders:order_step_one' %}">
                        {% trans 'Step 1. User requisites' %}
                    </a>
                </li>
                <li class="menu-item">
                    <a class="menu-link" href="{% url 'orders:order_step_two' %}">
                        {% trans 'Step 2. Way of delivery' %}
                    </a>
                </li>
                <li class="menu-item">
                    <a class="menu-link" href="{% url 'orders:order_step_three' %}">
                        {% trans 'Step 3. Payment method' %}
                    </a>
                </li>
                <li class="menu-item">
                    <a class="menu-link" href="{% url 'orders:order_step_four' %}">
                        {% trans 'Step 4. Order confirmation' %}
                    </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="Section-content">
          <form class="form" action="{% url 'orders-polls:order_step_one' %}" method="post">
            <div class="Order-block Order-block_OPEN" id="step1">
              <header class="Section-header Section-header_sm">
                <h2 class="Section-title">{% trans 'Step 1. User requisites' %}
                </h2>
              </header>
              <div class="row">
                <div class="row-block">
                  <div class="form-group">
                    <label class="form-label" for="name">
                        {% trans 'Name Surname' %}
                    </label>
                    {{ form.fio }}
                  </div>
                  <div class="form-group">
                    <label class="form-label" for="phone">{% trans 'Phone' %}
                    </label>
                      {{ form.phone }}
                      <span class="formerror">{{form.errors.phone}}</span>

                  </div>
                  <div class="form-group">
                    <label class="form-label" for="mail">{% trans 'E-mail' %}
                    </label>
                      {{ form.email }}
                      <span class="formerror">{{form.errors.email}}</span>
                  </div>
                </div>
                <div class="row-block">

                </div>
              </div>
              <div class="Order-footer">
                <button class="btn btn_success custom_login_btn-success" type="submit">{% trans 'Next' %}</button>
              </div>
              {% csrf_token %}
            </div>
          </form>
        </div>
      </div>
    </div>
    </div>
  </div>
{% endblock %}
{% block footer %}
{% include 'elems/footer.html' %}
{% endblock %}
{% block scripts %}
  <script src="{% static 'assets/plg/jQuery/jquery-3.5.0.slim.min.js' %}"></script>
  <script src="{% static 'assets/plg/form/jquery.form.js' %}"></script>
  <script src="{% static 'assets/plg/form/jquery.maskedinput.min.js' %}"></script>
  <script src="{% static 'assets/plg/range/ion.rangeSlider.min.js' %}"></script>
  <script src="{% static 'assets/plg/Slider/slick.min.js' %}"></script>
  <script src="{% static 'assets/js/scripts.js' %}"></script>
{% endblock %}

templates/orders_app/order_step_one_anonimous.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}
  {% trans 'Order step 1' %}
{% endblock %}

{%block header %}
  {% include 'elems/header.html' %}
{% endblock %}
{%block main %}
  <div class="Middle Middle_top">
    <div class="Middle-top">
      <div class="wrap">
        <div class="Middle-header">
          <h1 class="Middle-title">{% trans 'Order checkout' %}
          </h1>
          <ul class="breadcrumbs Middle-breadcrumbs">
            <li class="breadcrumbs-item"><a href="/">home</a>
            </li>
            <li class="breadcrumbs-item breadcrumbs-item_current"><span>{% trans 'Order checkout' %}</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="Middle Middle_top">

    <div class="Section Section_column Section_columnRight Section_columnWide Order">
      <div class="wrap">
        <div class="Section-column">
          <div class="Section-columnSection">
            <header class="Section-header">
              <strong class="Section-title">{% trans 'Overall progress' %}
              </strong>
            </header>
            <div class="Section-columnContent">
              <ul class="menu menu_vt Order-navigate">
                <li class="menu-item_ACTIVE menu-item">
                    <a class="menu-link" href="{% url 'orders:order_step_one' %}">
                        {% trans 'Step 1. User requisites' %}
                    </a>
                </li>
                <li class="menu-item">
                    <a class="menu-link" href="{% url 'orders:order_step_two' %}">
                        {% trans 'Step 2. Way of delivery' %}
                    </a>
                </li>
                <li class="menu-item">
                    <a class="menu-link" href="{% url 'orders:order_step_three' %}">
                        {% trans 'Step 3. Payment method' %}
                    </a>
                </li>
                <li class="menu-item">
                    <a class="menu-link" href="{% url 'orders:order_step_four' %}">
                        {% trans 'Step 4. Order confirmation' %}
                    </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="Section-content">
          <form class="form" action="{% url 'orders-polls:order_step_one_anonymous' %}" method="post">
            <div class="Order-block Order-block_OPEN" id="step1">
              <header class="Section-header Section-header_sm">
                <h2 class="Section-title">{% trans 'Step 1. User requisites' %}
                </h2>
              </header>
              <div class="row">
                <div class="row-block">
                  <div class="form-group">
                    <label class="form-label" for="name">
                        {% trans 'Name Surname' %}
                    </label>
                    <input class="form-input" id="name" name="name" type="text" value="{% trans 'John Doe' %}"/>
                  </div>
                  <div class="form-group require-field">
                    <label class="form-label" for="phone">{% trans 'Phone' %}
                    </label>
                      {{ form.phone }}
                      <span class="formerror">{{form.errors.phone}}</span>
                  </div>
                  <div class="form-group require-field">
                    <label class="form-label" for="mail">{% trans 'E-mail' %}
                    </label>
                      {{ form.email }}
                      <span class="formerror">{{form.errors.email}}</span>
                  </div>
                </div>
                <div class="row-block">
                  <div class="form-group require-field">
                    <label class="form-label" for="password">{% trans 'Password' %}
                    </label>
                    {{ form.password1 }}
                  </div>
                  <div class="form-group require-field">
                    <label class="form-label" for="passwordReply">{% trans 'Confirm Password' %}
                    </label>
                    {{ form.password2 }}
                    <span class="formerror">{{form.errors.password2}}</span>
                  </div>
                  <div class="form-group"><a class="btn btn_muted Order-btnReg" href="{% url 'profiles-polls:login' %}">{% trans "I've been already registered" %}</a>
                  </div>
                </div>
              </div>
              <div class="Order-footer">
                <button class="btn btn_success custom_login_btn-success" type="submit">{% trans 'Next' %}</button>
              </div>
              {% csrf_token %}
            </div>
          </form>
        </div>
      </div>
    </div>
    </div>
  </div>
{% endblock %}
{% block footer %}
{% include 'elems/footer.html' %}
{% endblock %}
{% block scripts %}
  <script src="{% static 'assets/plg/jQuery/jquery-3.5.0.slim.min.js' %}"></script>
  <script src="{% static 'assets/plg/form/jquery.form.js' %}"></script>
  <script src="{% static 'assets/plg/form/jquery.maskedinput.min.js' %}"></script>
  <script src="{% static 'assets/plg/range/ion.rangeSlider.min.js' %}"></script>
  <script src="{% static 'assets/plg/Slider/slick.min.js' %}"></script>
  <script src="{% static 'assets/js/scripts.js' %}"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>
{% endblock %}